galaxyproteomics/tools-galaxyp

tools/appendfdr/.shed.yml, tools/blast_plus_remote_blastp/.shed.yml, tools/dbbuilder/.shed.yml, tools/decoyfasta/.shed.yml, tools/digestdb/.shed.yml, tools/directag_and_tagrecon/.shed.yml, tools/fasta_merge_files_and_filter_unique_sequences/.shed.yml, tools/feature_alignment/.shed.yml, tools/filter_by_fasta_ids/.shed.yml, tools/idpqonvert/.shed.yml, tools/ltq_iquant_cli/.shed.yml, tools/maxquant/.shed.yml, tools/mgf_formatter/.shed.yml, tools/msconvert/.shed.yml, tools/myrimatch/.shed.yml, tools/peptideshaker/.shed.yml, tools/pepxml_to_xls/.shed.yml, tools/proteinpilot/.shed.yml, tools/protxml_to_xls/.shed.yml, tools/psm_eval/.shed.yml, tools/pyprophet/.shed.yml, tools/scaffold/.shed.yml, tools/spectrast2tsv/.shed.yml, tools/spectrast2tsv/tool_dependencies.xml
This should fix: https://github.com/galaxyproteomics/tools-galaxyp/issues/3
=> Add .shed.yml files

tools/peptideshaker/searchgui.xml
OK ... now I understand what was going on previously.  The pull request was backwards .. I thought I was asking to merge peptideshaker-temp into master but it was the other way around.  Sorry. This PR was what I meant to do.
=> Add tide to peptideshaker

tools/maxquant/maxquant.xml, tools/maxquant/maxquant_wrapper.py, tools/maxquant/tool_data_table_conf.xml.sample
Now the user has to run another tool before that creates an experimental design. Now MaxQuant could be used in a workflow building a dataset with the raws and passing the experimental design as an input argument.
=>  Changed the way input is get. 

suites/suite_swath_analysis/.shed.yml, suites/suite_swath_analysis/repository_dependencies.xml
This PR will add a Galaxy Tool Suite for SWATH-MS analysis.
The idea is to collect all tools necessary for a complete analysis and recommended from the GalaxyP community.
Please add all additional tools we will need.
=> add initial SWATH tool suite

tools/spectrast2spectrast_irt/.shed.yml, tools/spectrast2spectrast_irt/spectrast2spectrast_irt.xml, tools/spectrast2spectrast_irt/tool_dependencies.xml
This wrapper is work in progress. 
Does anyone have a small test input file?
@iracooke are these datatypes already included in `proeomics-datatypes`?
=> add initial version of spectrast2spectrast_irt wrapper

tools/peptideshaker/searchgui.xml
Björn, Ira,
We (Elvis and I) merged our SearchGUI tool wrapper with yours.
Let me know your thoughts on that,
Regards,
Gr.ben
=> pullrequest_searchgui

tools/peptideshaker/README.rst, tools/peptideshaker/searchgui.xml, tools/peptideshaker/tool_dependencies.xml
@bgruening Can you check this to see if it looks right?
=> Add LC_ALL setting to tool_dependencies for searchgui

tools/peptideshaker/peptide_shaker.xml, tools/peptideshaker/searchgui.xml
This is a fix for cluster environments suggested by Harald and Marc
=> Use temporary per-job copy of peptideshaker and searchgui packages

tools/hardklor/kronik.xml
This will probably couse some trouble down-stream. Like not rendering in the TS :)
=> Let's go without ö.

tools/blast_plus_remote_blastp/tools/repository_dependencies.xml, tools/decoyfasta/tools/repository_dependencies.xml, tools/directag_and_tagrecon/tools/repository_dependencies.xml, tools/ltq_iquant_cli/tools/repository_dependencies.xml, tools/mgf_formatter/tools/mgf_formatter/repository_dependencies.xml, tools/proteinpilot/repository_dependencies.xml, tools/protxml_to_xls/repository_dependencies.xml, tools/unipept/repository_dependencies.xml
These should be included in newer Galaxy releases.
=> remove proteomic datatypes

.tt_blacklist, tools/unipept/unipept.xml
=> Unipep testing

tools/morpheus/morpheus.xml
https://github.com/galaxyproject/galaxy/pull/3359#issuecomment-272198952
=> small fix encountered by @nsoranzo

tools/regex_find_replace/regex.py, tools/regex_find_replace/regex.xml, tools/regex_find_replace/regex_tabular.xml, tools/regex_find_replace/test-data/replace3.txt, tools/regex_find_replace/test-data/replace_tabular_2.txt
Allows inserting the dataset's display name into the dataset itself
=> Add support for #{input_name} token to regex_find_replace

tools/blast_plus_remote_blastp/tools/blast_plus_remote_blastp.xml
Need newer version to use -remote option to NCBI.  blast must be
compiled with GNUTLS to connect via https.
=> Update blast_plus_remote_blastp to 2.6.0

tools/unipept/unipept.py, tools/unipept/unipept.xml
Relies on d3_hierarchy Json subclass being added to
config/datatypes_conf.xml.sample for the Json output
https://github.com/galaxyproject/galaxy/pull/3580
=> Update Unipept with batched API requests and D3 JSON

tools/peptideshaker/searchgui.xml
Need to supply "-useGeneMapping 0"  when gene mapping is not desired.
=> searchgui fix GeneMapping params

tools/fasta_merge_files_and_filter_unique_sequences/fasta_merge_files_and_filter_unique_sequences.xml
Allows merging multiple input collections to create one output collection (using framework/workflow semantics)
=> Fix merge FASTA tool to support output collection

tools/fasta_merge_files_and_filter_unique_sequences/fasta_merge_files_and_filter_unique_sequences.xml
* Multiple input collections are only supported with multiple=True or <repeat> inputs
=> Fix my merge FASTA fix

tools/openms/FileMerger.xml
Fix `rep_param_raw_rt_custom`.
Remove `$rep_param_rt_concat_trafo_out`.
=> Fix issues with FileMerger

tools/openms/MetaProSIP.xml, tools/openms/macros.xml
fixes https://github.com/galaxyproteomics/tools-galaxyp/issues/182
=> fix for https://github.com/galaxyproteomics/tools-galaxyp/issues/182

tools/hardklor/datatypes_conf.xml
=> remove datatype conf, this is now upstream

tools/bumbershoot/idpquery/test-data/201203-624176-12-mm-gui-test-Gene-GeneId,Accession,DistinctPeptides.tsv, tools/bumbershoot/idpquery/test-data/201203-624176-12-mm-gui-test-GeneGroup-GeneGroup,GeneId,DistinctMatches.tsv, tools/bumbershoot/idpquery/test-data/201203-624176-12-mm-gui-test-Protein-Accession,FilteredSpectra,Description.tsv, tools/bumbershoot/idpquery/test-data/201203-624176-12-mm-gui-test-ProteinGroup-ProteinGroup,Accession,PercentCoverage.tsv
=> Remove trailing tab from headers

tools/openms/FidoAdapter.xml, tools/openms/readme.md
=> [fix] FidoAdapter.xml in OpenMS

tools/msgfplus/msgfplus.xml
I saw that @blankclemens had updated bioconda which meant I didnt have to do that myself 👍 Thanks and here comes the galaxy tool update.
=> New version for msgf+: 20170721

tools/bumbershoot/idpQonvertEmbedder.xml, tools/bumbershoot/idpassemble.xml
* Add ReporterIonMzTolerance and NormalizeReporterIons as isobaric-quantitation-specific options in idpQonvertEmbedder.xml
* Fix documentation formatting for idpassemble.xml
* Hide assembly and mapping inputs behind a boolean conditional in idpassemble.xml so that they don't expand workflow steps when unset
=> Update idpassemble and idpQonvertEmbedder

.travis.yml, tools/appendfdr/append_fdr.xml, tools/feature_alignment/feature_alignment.xml
* this will use travis stages
* newest Galaxy
* abort early
=> adjust travis testing

tools/bumbershoot/myrimatch.xml
ping @chambm, we briefly discussed this via hangout ...
Please feel free to add more.
=> add new peptide

tools/openms/MapAlignerPoseClustering.xml
=> Add MapAlignerPoseClustering

tools/flashlfq/flashlfq.xml
Change command to symlink spectrum files into relative dir: spectrum_dir
=> FlashLFQ can not handle path dirs with dots

tools/flashlfq/flashlfq.xml
@jj-umn we can keep this open a little bit and collect improvements if you like. 
Otherwise feel free to merge.
=> Upgrade flashlfq

tools/moFF/moff.xml
This fixes a pretty nasty bug in which the tool inputs were modified on disk. I'm now copying all inputs to temporary files to be extra safe.
=> bug fix - modified inputs

tools/peptideshaker/macros.xml, tools/peptideshaker/searchgui.xml
MSAmanda advanced options tested and available.
Changed "Fragment Tolerance Units" by default from 'ppm' to 'daltons' for comparability reasons and to avoid empty results with default options.
=> SearchGUI- MSAmanda advanced options available

tools/ThermoRawFileParser/.shed.yml, tools/ThermoRawFileParser/test-data/fake_input.txt, tools/ThermoRawFileParser/thermo_converter.xml
@CarlosHorro I think this tool is also from your group :)
The test is a huge fake, as I was not able to find a small RAW file.
=> Add Thermo converter

tools/unipept/unipept.py, tools/unipept/unipept.xml
=> Unipept4.0

tools/metaquantome/metaquantome_db.xml
A fix to the issue described [here](https://github.com/galaxyproteomics/metaquantome/issues/28).
=> Fix metaquantome_db

tools/peptideshaker/peptide_shaker.xml
Added option for exporting reports even when "zip" option is activated.
ptm_score_selector default value changed to PhosphoRS.
=> Option for exporting reports out of the zip file

tools/uniprotxml_downloader/uniprotxml_downloader.py, tools/uniprotxml_downloader/uniprotxml_downloader.xml
This should work for galaxy sites using https.
=> Access uniprot via https

tools/maxquant/mqwrapper.py, tools/maxquant_mqpar/mqwrapper.py
fixes https://github.com/galaxyproteomics/tools-galaxyp/issues/390
=> maxquant: use symlink instead of hard link

tools/maxquant/init.py, tools/maxquant/maxquant.xml, tools/maxquant/mqparam.py, tools/maxquant/mqwrapper.py, tools/maxquant_mqpar/init.py, tools/maxquant_mqpar/maxquant_mqpar.xml
fixes #392 and #393. For discussion on it and a demonstration of my magic git skills see #394
=> maxquant: checks on exp. design template + documentation + bugfix for identifier parse rules

.travis.yml, tools/cardinal/quality_report.xml
changed a bug that ocurred for some centroided files
changed TIC name
=> MSI QC small bug fixes

tools/pmd_fdr/PMD_FDR_package_for_Galaxy.R, tools/pmd_fdr/pmd_fdr.xml
=> pmd_fdr add Maxquant

tools/flashlfq/flashlfq.xml
Changes for FlashLFQ v1.0.0
A number of arguments have changed. Bayesian protein fold analysis has bee added.
=> Update flashlfq for v1.0.0

tools/pathwaymatcher/pathwaymatcher.xml
- to allow for `mv -t`
- also remove unnecessary redirections
=> pathwaymatcher: add coreutils

tools/hardklor/hardklor.py, tools/hardklor/hardklor.xml, tools/hardklor/kronik.xml
- fix cheetah quoting
- fix python code style
=> hardklor: add missing python requirement

tools/meta_proteome_analyzer/meta_proteome_analyzer.xml
stderr was redirected in order to be cat to stdout. in error case this never happens.
containerized test fails with pobably due to a font problem
```
Exception in thread "main" java.lang.InternalError: java.lang.reflect.InvocationTargetException
at java.desktop/sun.font.FontManagerFactory$1.run(FontManagerFactory.java:86)
at java.base/java.security.AccessController.doPrivileged(Native Method)
at java.desktop/sun.font.FontManagerFactory.getInstance(FontManagerFactory.java:74)
at java.desktop/sun.font.SunFontManager.getInstance(SunFontManager.java:247)
at java.desktop/sun.font.FontDesignMetrics.getMetrics(FontDesignMetrics.java:265)
at java.desktop/sun.swing.SwingUtilities2.getFontMetrics(SwingUtilities2.java:1231)
at java.desktop/javax.swing.JComponent.getFontMetrics(JComponent.java:1646) …
```
=> mpa: remove not working redicrections

tools/regex_find_replace/regex.py, tools/regex_find_replace/regex.xml, tools/regex_find_replace/regex_tabular.xml
and remove unused and deprecated import
=> regex: add missing py requirement

tools/pyprophet/pyprophet_export.xml, tools/pyprophet/pyprophet_score.xml
=> pyprophet score fixing apply weights

.github/workflows/ci.yaml, .github/workflows/pr.yaml
includes:
https://github.com/galaxyproject/tools-iuc/pull/2963
and the currently still unmerged:
https://github.com/galaxyproject/tools-iuc/pull/2976
https://github.com/galaxyproject/tools-iuc/pull/2940
=> sync github actions workflows with IUC

tools/unipept/unipept.py, tools/unipept/unipept.xml
Add interpro annotation.
unipept.py upgraded to python3
=> unipept version 4.3

.gitignore, tools/maxquant/macros.xml, tools/maxquant/maxquant.xml, tools/maxquant/mqparam.py, tools/maxquant/test-data/01/combined/txt/parameters.txt, tools/maxquant/test-data/01/config.yml, tools/maxquant/test-data/01/mqpar.xml, tools/maxquant/test-data/02/config.yml, tools/maxquant/test-data/02/mqpar.xml, tools/maxquant/test-data/03/config.yml, tools/maxquant/test-data/03/mqpar.xml, tools/maxquant/test-data/04/config.yml, tools/maxquant/test-data/04/mqpar.xml
Some improvements to the MaxQuant tool requested by the Schilling group at Freiburg
=> MaxQuant enhancements

.github/workflows/ci.yaml, .github/workflows/pr.yaml
`.tt_biocontainer_skip` was missing
=> add missing file and sync with IUC workflows

tools/maxquant/maxquant.xml
and giving examples in help section
=> MaxQuant: Changing parse rules to default

tools/pyprophet/pyprophet_export.xml
updated help and updated table in pdf, fixed one typo
=> Pyprophet export update

tools/bumbershoot/macros.xml
=> Update Bumbershoot to 3.0.20175

.github/workflows/ci.yaml, .github/workflows/pr.yaml
- R linting
- updated actions
- planemo test uses --no_dependency_resolution
is ` github.repository_owner == 'galaxyproteomics'` correct?
=> sync ci workflows with IUC

tools/msstats/msstats.xml
Correcting annotation file header names
=> MSstats: small fix and help update

tools/fastg2protlib/.shed.yml
Add advanced params to shed.yml to classify tool as suite.
=> Add suite params to shed.yml

tools/eggnog_mapper/data_manager/data_manager_eggnog.py
A fix for this error:
```
Traceback (most recent call last):
File "/blabla/toolshed.g2.bx.psu.edu/repos/galaxyp/data_manager_eggnog_mapper_abspath/9d5f039c637f/data_manager_eggnog_mapper_abspath/data_manager/data_manager_eggnog.py", line 65, in <module>
main()
File "/blabla/toolshed.g2.bx.psu.edu/repos/galaxyp/data_manager_eggnog_mapper_abspath/9d5f039c637f/data_manager_eggnog_mapper_abspath/data_manager/data_manager_eggnog.py", line 61, in main
open(args.config_file, 'wb').write(json.dumps(dm_dict))
TypeError: a bytes-like object is required, not 'str'
```
By the way, this data manager fails to download the hmm files as they have moved to a new domain, wget gets the 302 response but doesn't download the files:
```
Total wall clock time: 0.08s
Downloaded: 1 files, 917 in 0s (77.1 MB/s) …
```
=> EggNOG data manager: fix error

tools/dbbuilder/.shed.yml, tools/dbbuilder/dbbuilder.xml
- set wget version
- fix shed.yml urls
- remove ebi download option (dysfunctional and there seem to be specialized tools nowadays)
=> dbbuilder fixes

tools/psm_validation/macros.xml, tools/psm_validation/psm_validation.xml
Modify label text for clarity "Epsilon" -> "Fragment Tolerance"
=> Modify tolerance label text per user feedback

.github/workflows/ci.yaml, .github/workflows/pr.yaml, .github/workflows/slash.yaml
Currently workflows do not run anymore, since github disabled `set-env`.
=> sync github actions workflows with latest IUC version

tools/metaquantome/macros.xml, tools/metaquantome/metaquantome_db.xml, tools/metaquantome/metaquantome_viz.xml
one of the tools failing weekly CI
=> mataquantome viz: fix variable access

tools/dbbuilder/dbbuilder.xml
This removes an unnecessary option in the dbbuilder tool.
=> Remove complete proteome set option.

tools/meta_proteome_analyzer/meta_proteome_analyzer.xml
with 
- all options
- better OOM detection taken from here https://github.com/galaxyproteomics/tools-galaxyp/pull/528
TODO:
=> MPA: upgrade to 2.0 

.github/workflows/ci.yaml, .github/workflows/pr.yaml
and restore test data creation in PR and CI workflow
=> sync github actions with IUC

tools/meta_proteome_analyzer/meta_proteome_analyzer.xml
alternatively the bioconda wrapper script should be adapted to
respect the environment variable
=> MPA remove Xmx option

.github/workflows/ci.yaml, .github/workflows/pr.yaml
=> fix typo in CI workflows

tools/pyteomics/.shed.yml, tools/pyteomics/mztab2tsv.xml, tools/pyteomics/mztab_reader.py, tools/pyteomics/test-data/1.mztab, tools/pyteomics/test-data/2.mztab
=> add mztab2tsv

.github/workflows/ci.yaml, .github/workflows/pr.yaml
broke due to grouping in chunked ci_find_tools
=> fix workflows (test data genertion)

tools/encyclopedia/encyclopedia_encyclopedia.xml, tools/encyclopedia/encyclopedia_fasta_to_prosit_csv.xml, tools/encyclopedia/encyclopedia_library_to_blib.xml, tools/encyclopedia/encyclopedia_prosit_csv_to_library.xml, tools/encyclopedia/encyclopedia_quantify.xml, tools/encyclopedia/encyclopedia_searchtolib.xml, tools/encyclopedia/encyclopedia_walnut.xml, tools/encyclopedia/macros.xml
Update encyclopedia to version 1.2.2
Use IUC guidelines for tokens:  @TOOL_VERSION@ and @VERSION_SUFFIX@
=> Update encyclopedia to version 1.2.2

.github/workflows/ci.yaml, .github/workflows/pr.yaml
=> sync with IUC CI and use 21.05

tools/msstatstmt/msstatstmt.xml
Small change in the help text.
=> Fix help text in MSStatsTMT

tools/metanovo/metanovo.xml
VERSION_SUFFIX was define but not used.
=> Fix version suffix

tools/proteomiqon_psmbasedquantification/proteomiqon_psmbasedquantification.xml
This PR upgrades the tool version of proteomiqon_psmbasedquantification to 0.0.8.
=> Update proteomiqon_psmbasedquantification to version 0.0.8

tools/proteomiqon_mzmltomzlite/proteomiqon_mzmltomzlite.xml
This PR upgrades the tool version of proteomiqon_mzmltomzlite to 0.0.8.
=> Update proteomiqon_mzmltomzlite to version 0.0.8

tools/proteomiqon_proteininference/proteomiqon_proteininference.xml, tools/proteomiqon_proteininference/test-data/result_1.json, tools/proteomiqon_proteininference/test-data/result_2.json, tools/proteomiqon_proteininference/test-data/result_3.json, tools/proteomiqon_proteininference/test-data/result_4.json, tools/proteomiqon_proteininference/test-data/result_5.json
This PR fixes a bug that caused no collection being returned in multi file mode.
=> Fix multi file mode in proteomiqon_proteininference

tools/proteomiqon_psmstatistics/proteomiqon_psmstatistics.xml, tools/proteomiqon_psmstatistics/test-data/result_1.json, tools/proteomiqon_psmstatistics/test-data/result_2.json
This PR updates proteomiqon_psmstatistics to version 0.0.8
=> Update proteomiqon_psmstatistics to version 0.0.8

tools/mqppep/macros.xml, tools/mqppep/mqppep_anova_script.Rmd
- adjusted graphics sizes
- improved handling of single-substrate enriched kinases
- removed unwise 'as.numeric'
- bumped version number
=> update to v0.1.14

tools/dbbuilder/dbbuilder.xml
Fix the uniprokb query syntax.
=> dbbuilder Fix the uniprokb query syntax

tools/uniprotxml_downloader/macros.xml, tools/uniprotxml_downloader/uniprotxml_downloader.py, tools/uniprotxml_downloader/uniprotxml_downloader.xml
- Updates script to use newer uniprot API.
- Adds field option and parameter to python script and Galaxy tool that specifies if IDs or names are provided for query.
=> Update uniprotxml_downloader to use new Uniprot API

tools/openms/macros.xml
=> bump for OpenMS2.8 deployment

tools/maxquant/macros.xml, tools/maxquant/test-data/03/mqpar.xml, tools/maxquant/test-data/05/mqpar.xml, tools/maxquant/test-data/06/mqpar.xml, tools/maxquant/test-data/07/mqpar.xml, tools/msstats/msstats.xml, tools/msstatstmt/msstatstmt.xml
I've added https://pubs.acs.org/doi/10.1021/acs.jproteome.2c00051 to the references (and did some small changes regarding the version suffix in MSStats and MSStatsTMT).
=> Add new reference for MaxQuant, MSStats and MSStatsTMT

tools/mqppep/MaxQuantProcessingScript.R, tools/mqppep/macros.xml, tools/mqppep/mqppep_anova.R, tools/mqppep/mqppep_anova.xml, tools/mqppep/mqppep_anova_script.Rmd
grey-out NAs; remove NA labels; fix kinase names duplicated because of character-case variation; use 'sites' where 'substrates' may be inappropriate; appease linters
=> cosmetic improvements to presentation

tools/qupath_roi_splitter/qupath_roi_splitter.py, tools/qupath_roi_splitter/qupath_roi_splitter.xml
I accidentally included a bug in the Galaxy version that has already been fixed.
=> Fix QuPath ROI Splitter

tools/eggnog_mapper/eggnog_macros.xml, tools/eggnog_mapper/eggnog_mapper/eggnog_mapper_search.xml
I forgot the most important part in https://github.com/galaxyproteomics/tools-galaxyp/pull/676.
=> skip annotation for search mode

tools/diann/diann.xml
- Changed FASTA database input to optional (since search can be done with a predicted library w/o a FASTA db) + fix for having no FASTA db as input 
- Increased BioContainer version
- Removed all experimental features, to be in line with the licence (just commented out)
=> Update DIA-NN wrapper

tools/unipept/unipept.xml
Hi all,
This PR links the tools to its bio.tools entry: https://bio.tools/unipept
Bérénice
=> Add bio.tools for unipept

tools/mz_to_sqlite/.shed.yml, tools/mz_to_sqlite/mz_to_sqlite.xml
Hi all,
This PR links the tools to its bio.tools entry: https://bio.tools/mztosqlite
Bérénice
=> mzToSQLite biotools

tools/msstats/msstats.xml
Hi all,
This PR links the tools to its bio.tools entry: https://bio.tools/msstatstmt
Bérénice
=> Add bio.tools for msstatstmt

tools/metaquantome/macros.xml, tools/metaquantome/metaquantome_db.xml, tools/metaquantome/metaquantome_expand.xml, tools/metaquantome/metaquantome_filter.xml, tools/metaquantome/metaquantome_sample.xml, tools/metaquantome/metaquantome_stat.xml, tools/metaquantome/metaquantome_viz.xml
Hi all,
This PR links the tools to its bio.tools entry: https://bio.tools/metaquantome
Bérénice
=> Add bio.tools for metaquantome

tools/metagene_annotator/.shed.yml, tools/metagene_annotator/convert_mga.py, tools/metagene_annotator/metagene_annotator.xml
Hi all,
This PR fixes the link to the bio.tools entry
Bérénice
=> Fix metageneannotator bio.tools

tools/qupath_roi_splitter/qupath_roi_splitter.py, tools/qupath_roi_splitter/qupath_roi_splitter.xml
Update to v0.2.0 (--fill and --all arguments added). See https://github.com/npinter/ROIsplitter.
=> Update QuPath ROIsplitter

tools/metanovo/metanovo.xml
Hi all,
This PR links the tools to its bio.tools entry: https://bio.tools/metanovo
Bérénice
=> Add bio.tools for metanovo

tools/qupath_roi_splitter/qupath_roi_splitter.py, tools/qupath_roi_splitter/qupath_roi_splitter.xml
Update to 0.3.0 see https://github.com/npinter/ROIsplitter
=> Update ROIsplitter to 0.3.0

tools/ThermoRawFileParser/thermo_converter.xml
Added the bio.tools xref to enable EDAM annotations of the tool.
=> Added bio.tools ref to ThermoRawFileParser
