- tools/msconvert/msconvert.xml
- tools/msconvert/msconvert_wrapper.py
Did the minimal to add conversion of wiff datasets.   
This relies on the Wiff datatype having files named wiff and wiff_scan in the extra_files_path, 
and requires the input_names to have the .wiff and .wiff.scan extensions.
The option --implicit was added to  msconvert_wrapper.py in order to include the .wiff.scan file in the correct directory/filename but not to add it to the mscovert application command line.
> Add support for converting the Wiff datatype to the msconvert tool.

- tools/peptideshaker/peptide_shaker.xml
This should be a safe-guard to not confuse peptide-shaker during different instances.
> Use multiple temp directories

- tools/peptideshaker/macros.xml
Trivial fix for those of us who still use old instruments
> Fix precursor mass switch when using Daltons

- .gitignore
- .travis.yml
This PR will:
* add a gitgnore file
* enables `planemo lint` on all PR via travis
For the latter `travis` integration needs to be activated in this repository. @trevor can you please do this, if we agree we want to merge this? 
We had some very good experiences with this kind of testing in the IUC repository.
> Repository setup

- tools/peptideshaker/peptide_shaker.xml
This is needed because msamanda wants to write to `~/.msamanda`
ping @iracooke
> overwride $HOME dir to the cwd

- packages/package_peptideshaker_1_1/tool_dependencies.xml
This is needed because we are inside the folder after downloading.
> Update peptideshaker tool_dependencies.xml

- packages/package_msgfplus_v10089/.shed.yml
- packages/package_msgfplus_v10089/tool_dependencies.xml
- tools/msgfplus/.shed.yml
- tools/msgfplus/COPYING
- tools/msgfplus/msgfplus.xml
- tools/msgfplus/test-data/201208-378803-msgf-2mmu-tryptic-many_mods.mzid
- tools/msgfplus/test-data/201208-378803-msgf-50ppm-semitryptic-no_mods.mzid
- tools/msgfplus/test-data/input/201208-378803.mzML
- tools/msgfplus/test-data/input/cow.protein.PRG2012-subset.fasta
- tools/msgfplus/tool_dependencies.xml
- add package_msgfplus_v10089
- add example output (created by searching symlinks to the Myrimatch input files)
- add common and custom mod parameters
- add functional tests
I recognize this PR may controversial as it is functionally quite redundant with Ira's MSGF wrapper. I created a standalone wrapper in galaxyp rather than forking Ira's protk version because I am doing (relatively) frequent docker deployments. Doing enough of those, it got to the point where downloading and building ruby/protk was an unnecessary delay. It also lets me make changes without juggling another repository, and it's decoupled from ProteoWizard: why not have idconvert in a separate tool? I guess because it's expected to feed the output to the TPP in the protk suite. But then why not also have TPP as a tool …
> - add standalone msgfplus wrapper that doesn't require protk

- tools/hardklor/datatypes_conf.xml
This is a small fix to address the incorrectly specified datatype modules in hardklor's datatypes_conf.xml.
> Fix erroneous module name for Tabular datatype

- tools/msgfplus/msgfplus.xml
Hi, our lab does quite a bit of MSGF+ searches using prefractionated databases matched with prefractionated spectra (by isoelectric point). We use our own MSGF+ tool XML but it would be nice if this could be in the toolshed instead. The tool takes as input either a spectra and a fasta dataset, or a dataset_collection of a pair of spectra/fasta.
There are 2 problems with this PR:
+ Breaks workflows/automation by moving the `params` inside a `conditional`
+ I cannot get the planemo tests to work (but the tool works inside galaxy)
> Msgf+ on mzml/fasta pairs

- tools/dbbuilder/tool-data/uniprot_taxons.loc.sample
Several strains were added that commonly contaminate cell culture ([Drexler and Uphoff, 2002](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3463982/)).
> Added several mycoplasma strains

- tools/peptideshaker/searchgui.xml
symbolic links to mgf input files for searchgui can not look like a
file path.
Issue occurred when uploading mgf files via URL.
> searchgui sanitize input display names

- tools/bumbershoot/myrimatch/myrimatch.xml
Calling as -OutputFormat 'mzid' throws an error (should be 'mzIdentML')
> fixed incorrect parameter format for mzIdentML output

- tools/openms/ITRAQAnalyzer.xml
- tools/openms/IsobaricAnalyzer.xml
- tools/openms/TMTAnalyzer.xml
Added quote marks to activation methods in tool cheetah since this contains values with whitespace in almost all options. Without this, the tool crashes.
> Bugfix for openMS

- tools/openms/IDFileConverter.xml
- tools/openms/readme.md
Unfortunately, IDFileConverter detects the input type according to the file extension, which is not working with Galaxy. This is a work around which should work in common cases (e.g. mzid, idxml).
> Fix IDFileConverter

- tools/percolator/nested_collection.py
- tools/percolator/nested_collection.xml
This PR:
+ Changes to continuous numbering of the inner datasets in nested lists, for all files belonging to the same "pool" (or sample set, biological set), as determined by regex. So not `inputfn0..2` in each batch, but the second batch will have `inputfn3..5`, if it belongs to the same pool.
+ Adds full display name of datasets to the those `inputfn` datasets, making them `inputfn1_your_spectra.mzML` for easier sample tracking
+ Adds zero-padding to file numberings so discover datasets uses the correct order when discovering the lists. Otherwise `inputfn10` will come before `inputfn5`.
Planemo tests pass locally, but I want to give it a try on my galaxy installation as well via the testtoolshed, will notify here when it has been tested.
> Better sample tracking nested collections

- tools/dbbuilder/dbbuilder.xml
- tools/dbbuilder/tools/dbbuilder.xml
Add metaproteome downloads to this tool.  
Allow URL download of compressed fasta data.  
We may eventually want to replace the unix commands with a python script.  This would allow this tool to work from galaxy server hosted on MacOSX, and compression could be detected and automatically handled.
> Dbbuilder metaprot

- tools/peptideshaker/macros.xml
- tools/peptideshaker/peptide_shaker.xml
Target 2017_04_01 release:
SearchGui:3.2.13
PeptideShaker:1.16.4
Add  -ptm_score None
Add  -ptm_sequence_matching_type
> peptideshaker - Add ppm option, 2017_04_01 release

- tools/percolator/nested_collection.xml
Nested collection creator has a regex to get nested list identifiers. Except that regex doesnt like names with characters other than `[\w.]`, or in other words `[a-zA-Z0-9_.]`. Typically filenames are used, and I added here the `-` hyphen/dash/minus character which is not uncommon and allowed in filenames.
If you can think of any other character which may show up in a filename, please tell or commit.
> Allow dash/hyphen/minus in a filename

- tools/pi_db_tools/README.rst
- tools/pi_db_tools/delta_pi_calc.xml
- tools/pi_db_tools/peptide_pi_annotator.py
- tools/pi_db_tools/pi_database_splitter.py
- tools/pi_db_tools/pi_db_split.xml
This PR changes the interface to the pI (isoelectric point) based fractionation of databases and the calculation of delta pI for peptides. It makes possible:
- using columns by name-pattern, doing a simple `pattern in columnname` check, aside the column number input
- making possible using the db splitter with multiple IPG ranges as a repeat, when input peptide tables have different IPG ranges.
> Hirieftools multi-IPG strip and column patterns

- tools/msgfplus/msgfplus.xml
This PR updates the msgfplus.xml tool.
1 - help text was wrong about forward and reverse input
2 - usage of `display_name` is not recommended, marius told me on gitter to use `element_identifier` mostly
3 - Add `.mzML` to the input file name because msgfplus crashes when the extension is wrong and sometimes element identifiers do not contain the mzML extension.
> Small update to msgfplus

- tools/bumbershoot/idpassemble/README.md
- tools/bumbershoot/idpqonvert/README.md
- tools/bumbershoot/idpquery/README.md
- tools/bumbershoot/myrimatch/README.md
This should also get idpQuery into MTS. Not sure why idpQonvert and idpAssemble are there but not idpQuery.
> Fix link to IDPicker website and remove my VU affiliation

- tools/msgfplus/msgfplus.xml
The old output schema resulted in output named "forward.mzML" since that is the unchangeable name of the paired element that was the spectra dataset.
I changed to use the `name` attribute of the element containing the dataset pair, which results in proper spectra file names. I use `name` and not `element_identifier` since the element itself is a collection and will raise a KeyError if `element_identifier` is used.
A bit annoying this didnt end up in yesterdays PR.
> Naming output of MSGFplus paired spectra/db better

- tools/peptideshaker/searchgui.xml
SearchGUI needs `zip`, see: https://github.com/bernt-matthias/tools-galaxyp/blob/0a0c1b53f934a0edfc7f18e9c401ad353a44092a/tools/peptideshaker/searchgui.xml#L419. This has been added before: 
https://github.com/galaxyproteomics/tools-galaxyp/commit/87d3dffcc9ef41e1f7c8488d1939165056f19413#diff-ec5346afe3992b199241a92092c2e047
but unfortunately removed later
https://github.com/galaxyproteomics/tools-galaxyp/commit/a2bd191e342173a297b0d60caa09bd4826239ad5#diff-ec5346afe3992b199241a92092c2e047
> (re)added zip as requirement of SearchGUI

- tools/msgfplus/msgfplus.xml
Hi.
Our MSGF+ wrapper had a bug when using custom mods with more than one `aa_specificity`. I fixed this and adapted the last test accordingly. Instead of comparing the diff, the test looks for the identification of the custom mods now.
Cheers, Flo
P.S.: My first steps into Python/Cheetah!
> Fixed Msgf custom modification with multiple aa_specificities

- tools/openms/MSGFPlusAdapter.xml
The wrapper for MSGFPlusAdapter allowed only one variable modification, although the tool can take an process several. 
This fix solves part of https://github.com/galaxyproteomics/tools-galaxyp/issues/209
> Allow for multiple variable modifications in MSGFPlusAdapter

- tools/openms/XTandemAdapter.xml
Like in the MSGFPlusAdapter, we had an incorrect restriction that allowed for only one variable modification. Compare https://github.com/galaxyproteomics/tools-galaxyp/pull/210
> Fixed XTandemAdapter: deleted restriction to only one variable mod

- tools/eggnog_mapper/eggnog_mapper.xml
The column headers in `annotations` changed in 1.0. and I missed it in the original wrapper.
> fix column headers in eggnog-mapper

- tools/flashlfq/flashlfq.xml
The FlashLFQ code only put a single column header “test”  which causes
galaxy to interpret  this as a 1-column tabular file.
> FlashLFQ remove header line from QuantifiedProteins.tsv

- tools/peptideshaker/macros.xml
- tools/peptideshaker/peptide_shaker.xml
- tools/peptideshaker/searchgui.xml
SearchGUI from 3.2.13 to 3.2.24
PeptideShaker from 1.16.17 to 1.16.20
And:
SearchGUI`s galaxy tool improvements: Myrimatch advanced options following desktop app. model, more Tide exporting options (MzIdentML and Percolator)
> Updated references SearchGUI from 3.2.13 to 3.2.24, PeptideShaker from 1.16.17 to 1.16.20

- tools/openms/macros.xml
I'm not sure if all tools involve java. Then this should be fine. Alternatively the oom tests could be applied only for java based tools. 
I'm doing this in particular for MSGFPlusAdapter
> openms: added out of memory tests

- tools/moFF/moff.xml
@caleb-easterly and @jj-umn this PR will make the moff tool independent of the display_name. I got several error reports of people getting errors because the display name had no file ending.
> Make moff independent of the display name file-endings

- tools/quantp/quantp.xml
Having some packaging requirements on [z.umn.edu/proteogenomicsgateway](z.umn.edu/proteogenomicsgateway) that need a higher version so I specified it with this update.
> added munsell package requirement to QuanTP

- .travis.yml
- tools/msconvert/msconvert_macros.xml
It's easy to change the tar filename after creating it and the dataset name after uploading it. This would break msconvert which assumed the file/folder inside to be named the same as the tar or data set (minus the tar extension). This patch makes it pass msconvert a pathmask based on the datatype. Technically this shortcut (using wildcards) could produce multiple outputs if someone put multiple raw files in a tar. But a more sophisticated approach - which actually tried to pick the real file/folder in the tar - would only improve matters by virtue of throwing a meaningful error if a tar includes multiple raw files.
> Fix msconvert where tar filename or dataset name have changed

- tools/metaquantome/metaquantome_db.xml
- tools/metaquantome/metaquantome_expand.xml
Just some minor fix suggestions in the help documentation for the expand and database modules.
For the database module, I wasn't entirely sure what this describes:
> Also, note that the databases will be stored and not modified, so the date of download can be referenced later. The important exception to this is the NCBI database, which is updated every time it is loaded by the ete3 package, used within metaQuantome.
Does this mean that the NCBI database is built in to metaQuantome? In other words, it is not downloaded into the output Galaxy dataset?
Also, I saw that the visualize module does not get the correct column for the **Taxonomic rank to restrict to in the plot** in the **Taxonomic analysis** mode. As it is on MPG, I see that it gets the namespace column (index 3 I believe). Seems …
> update metaquantome help documentation

- tools/cardinal/preprocessing.xml
- tools/openms/LowMemPeakPickerHiResRandomAccess.xml
While this style is currently tolerated by Galaxy, it prevents correct param format detection in the API and, thus, interferes with scripts trying to extract meaningful info from your tool wrappers.
Autodetection of the pattern also fixed a param label :-)
> Remove list-style terminating ,s from format attributes

- tools/peptideshaker/peptide_shaker.xml
Leads to the following otherwise
```
Invalid Syntax
Line 129, column 20
Line|Cheetah Code
----|-------------------------------------------------------------
126 |            #end if
127 |            #if '2' in $output_reports_list:
128 |                && find \$cwd/output_reports -name '*Default_PSM_Phosphorylation_Report.txt' -exec bash -c 'mv "$0" "psm_phospho.txt"' {} \;
129 |            #end if`
^
130 |            #if '3' in $output_reports_list:
131 |                && find \$cwd/output_reports -name '*Default_PSM_Report.txt' -exec bash -c 'mv "$0" "psm.txt"' {} \;
132 |            #end if
```
> Fix typo in peptideshaker

- tools/ThermoRawFileParser/thermo_converter.xml
- also remove superficial redirections
- by setting the ftype in the tests the warnings
`Datatype class not found for extension 'raw'`
disappear
> thermorawfileparser: fix capitalization of requirement

- tools/flashlfq/flashlfq.xml
In the containerized test the logfile contains
```
Problem opening .mzML file ./spectrum_dir/sliced-mzml.mzML; One or more errors occurred.
```
which is now at least detected. Problem still persists. Odd thing is that some output files are still produced... maybe non-fatal error?
> flashlfq: detect mzML reading error

- tools/regex_find_replace/regex_tabular.xml
Hi galaxyp, regexColumn was failing tests when we upgraded regex_find_replace.  The tests pass with this fix.  Regards, Catherine (Galaxy Australia)
> Fix typo in regex_tabular.xml command

- tools/mz_to_sqlite/mz_to_sqlite.xml
Update: mztosqlite executor.awaitTermination flow modified to better handle large data sets processed in low resource environments. Especially when run with only 1 thread. This updates to revised recipe version
> Allow only mgf scans, update latest version of jar

- tools/mz_to_sqlite/README.md
- tools/mz_to_sqlite/mz_to_sqlite.xml
Modified xml from using coded -Xms<n> -Xmx<n> values to relying on _JAVA_OPTIONS environment variable.
Increased version number.
> Remove coded JVM heap options, rely on _JAVA_OPTIONS

- tools/pepquery/macros.xml
- tools/pepquery/pepquery.xml
Add capability to report Spectrum Scan Title instead of scan index.
> Update PepQuery to version 1.6

- tools/ThermoRawFileParser/thermo_converter.xml
The tool always produces now collections in order to avoid problems working with workflows and variable inputs.
Changed some input and output names in order to have clearer names.
Some code cleaning.
> ThermoRawFileConverter tool: always returns collections

- tools/openms/macros.xml
I remember that agressive error checkking is not an option, so I added only this one.
> openms: also detect oom for C++ tools

- tools/msconvert/msconvert.xml
- tools/msconvert/msconvert_macros.xml
I successfully got msconvert running via singularity this way (thanks to @sneumann and @bgruening). I'm wondering if there is a way around the sudo stuff. From Galaxy sine one could do this with a call to the external_chown script (https://github.com/galaxyproject/galaxy/blob/dev/scripts/external_chown_script.py) which runs anyway in realuser setups. 
Also I'm not sure if there is a better way than to copy the wineprefix stuff .. 
(with "sucessfuly" I mean that checked the first 2 tests manually :))
Further ideas:
- probably we should clean the created tmpdir after the tool run via a trap
- maybe we use a more standard label for the outputs
> changes for msconvert to make it runnable via singularity

- tools/pyteomics/mztab2tsv.xml
- tools/pyteomics/mztab_reader.py
Refactored `read_mztab` to write an empty `tsv` file instead of a file with an empty string when some table is missing. To avoid a lot of repeating `if` conditions iteration over the tables is now done with `__iter__` method of `MzTab` class from pyteomics.
> read_mztab is refactored

- tools/peptideshaker/README.rst
- tools/peptideshaker/macros_basic.xml
- tools/peptideshaker/searchgui.xml
SearchGUI updated to v4.0.12
PeptideShaker updated to v2.0.9
SearchGUI now configures temp and log folders into the working directory.
> Update SearchGUI to 4.0.12 & PeptideShaker to 2.0.9

- tools/ThermoRawFileParser/test-data/really_small.indexed_mzML
- tools/ThermoRawFileParser/test-data/really_small.mzml
- tools/ThermoRawFileParser/test-data/really_small_ext.mzml
- tools/ThermoRawFileParser/thermo_converter.xml
this includes a rollback of the underlying change that broke compatibility between some of the critical projects in this space (https://github.com/compomics/ThermoRawFileParser/wiki/ReleaseNotes)
+ regenerate test data in addition to version
I understand the failures except the one below. Could this be caused by the following entry in the release notes?
> Disable peak picking for specified MS levels
```
-      <offset idRef="controllerType=0 controllerNumber=1 scan=3">13470</offset>
-      <offset idRef="controllerType=0 controllerNumber=1 scan=4">18165</offset>
-      <offset idRef="controllerType=0 controllerNumber=1 scan=5">23275</offset>
-      <offset idRef="controllerType=0 controllerNumber=1 scan=6">27236</offset>
-      <offset idRef="controllerType=0 controllerNumber=1 …
```
> update thermo converter to 1.3.4

- tools/metaquantome/macros.xml
This allows the viz module to handle column names starting with a digit.
> Upgrade metaquantome to version 2.0.2

- tools/maxquant/macros.xml
- tools/maxquant/maxquant.xml
- tools/maxquant/test-data/03/config.yml
- tools/maxquant/test-data/05/config.yml
- tools/maxquant/test-data/05/mqpar.xml
A parameter was changed from `lfqSkipNorm` to `lfqNormType` in 1.6.17.0. Default value for `lfqSkipNorm` in earlier MQ versions was `false` (Skip normalization). Default value in 1.6.17.0 for `lfqNormType` is `Classic`, which is equivalent to `lfqSkipNorm = false`. This PR changes the default selection of `lfqSkipNorm` to `Classic` in the Galaxy wrapper.
> Update MaxQuant 1.6.17.0

- tools/maxquant/macros.xml
- tools/maxquant/maxquant.xml
Thermo RAW files have some incompatibilities with soft links and the dotnet dependency. The workaround is to simply copy files instead of sym link them. Older MaxQuant versions (<=1.6.10.43) are not affected by this. Some Thermo DLLs were updated in 1.6.17.0 compared to 1.6.10.43, maybe the problem relies here.. (f.e. ThermoFisher.CommonCore.RawFileReader.dll 3.0.59.0 -> 5.0.0.38).
> Fix MaxQuant 1.6.17.0

- tools/peptideshaker/macros_basic.xml
- tools/peptideshaker/peptide_shaker.xml
- tools/peptideshaker/searchgui.xml
SG:
Last updates on SG application and Conda package have fixed diverse errors running DirectTag, MsAmanda, Myrimatch and OMSSA.
Last MsAmanda versions are based on .NET Core, and some issues generating bundles with .NET Core 5 for macosx have caused errors leading to remove it from the Conda package for macosx until .NET Core 6 has been released.
Many other minor updates.
PS:
PeptideShaker bugfix managing searchgui files with different parameter name than the previously fixed one.
> SG updated to v4.0.41 && PeptideShaker updated to v2.0.33.1

- tools/proteomiqon_peptidespectrummatching/proteomiqon_peptidespectrummatching.xml
This PR attempts to fix the image not showing in the help section of the Proteomiqon PeptideSpectrumMatching tool, found here: https://usegalaxy.eu/root?tool_id=proteomiqon_peptidespectrummatching
To solve the issue, I took a look at https://github.com/galaxyproject/tools-iuc/blob/master/tools/bedtools/slopBed.xml and saw that they prefixed images with $PATH_TO_IMAGES/ so I followed that practice.
If this is not the cause of the image not showing up, please let me know.
> Fix image not showing in proteomiqon_peptidespectrummatching

- tools/pepquery/macros.xml
protein modifications aren't working in pepquery, removing them to reduce chance of user error.
> Remove protein modification options

- tools/metanovo/metanovo.xml
This `import re` line was left out duplicating changes from the testing environment for the initial MetaNovo commit earlier today.
> Import re module.

- tools/metanovo/metanovo.xml
After updating the initial PR to replace certain characters in input filenames, I failed to retest the collection input logic (MetaNovo can run on multiple files), and it was broken.
This makes a good case for adding automated tests soon.
> Fix symlinking of collection files.

- tools/eggnog_mapper/data_manager_eggnog_mapper/data_manager/data_manager_eggnog.xml
- tools/eggnog_mapper/data_manager_eggnog_mapper_abspath/data_manager/data_manager_eggnog.xml
- tools/eggnog_mapper/eggnog_macros.xml
- tools/eggnog_mapper/eggnog_mapper/eggnog_mapper.xml
- tools/eggnog_mapper/eggnog_mapper/test-data/DIA_nlim.emapper.annotations_orthologs
- tools/eggnog_mapper/eggnog_mapper/test-data/scoped.emapper.annotations_orthologs
user reported an error where eggnog reported that a `diamond blastp`
call failed. when executing the failing call I get
```
diamond v2.0.11.149 (C) Max Planck Society for the Advancement of Science
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)
Scoring parameters: (Matrix=BLOSUM62 Lambda=0.267 K=0.041 Penalties=11/1)
Temporary directory: No such file or directory
Error: Error opening temporary file /gpfs1/work/songalax/galaxy/database/jobs_directory/000/155/155782/working/emappertmp_dmdn_OnTm_q/diamond-tmp-i7fCqW
```
Release notes indicate that a tmpdir related bug was fixed:
https://github.com/eggnogdb/eggnog-mapper/releases
overall 2.1.7 and 2.1.8 seem to be a bugfix releases
> bump eggnog

- tools/maxquant/macros.xml
- tools/maxquant/maxquant.xml
- tools/maxquant/maxquant_mqpar.xml
Both maxquant and maxquant_mqpar call on the python scripts create_mqpar.py and modify_mqpar.py.  Both scripts require another file, mqparam.py but pulsar will not copy this file because it is not referred to by name in the tool command.
> Add required_files for maxquant an maxquant_mqpar

- tools/dbbuilder/dbbuilder.xml
@jj-umn @bernt-matthias we have a problem here. The uniprot API has changed. 
I could not quickly find a way to download everything in one go. It seems the UniProt API is limited to 500 entries per request.
And other things have also changed.
> fix the uniprot URL

- tools/msconvert/README.md
The current README says that we need ProteoWizard installed on our machines in order to run msconvert. This info is out of date since we can run it using the docker container.
> Update msconvert README.md

- .github/workflows/pr.yaml
- tools/maxquant/macros.xml
- tools/maxquant/maxquant.xml
- tools/maxquant/maxquant_mqpar.xml
In July, we missed the case in the file-type for `mzxml` for the `maxquant_mqpar` tool (we only fixed `maxquant`).  Consequently, the workflow editor won't allow connections to this input for `mzxml` files.
> fixed case of mzxml and mzml in maxquant_mqpar tool

- .github/workflows/pr.yaml
Hope this mistake only affected the openms run (https://github.com/galaxyproteomics/tools-galaxyp/actions/runs/3566803536)  .. which is unfortunate enough. 
I hope that restarting the workflow for OpenMS will use the new version after merging this one ...
> fix owner for deploy job

- tools/regex_find_replace/regex.xml
- tools/regex_find_replace/regex_tabular.xml
Version 1.0.2 of the tool uses format="input" in its output declaration. This creates an output with data type "input". I figure, the intention is instead to create an output with the same data type as the input. This should fix it, right?
Incidentally, this same error can currently be found in the Tool XML documentation.
> regex find/replace: use format_source for output

- tools/mqppep/MaxQuantProcessingScript.R
- tools/mqppep/macros.xml
- tools/mqppep/mqppep_preproc.xml
One parameter that applied to two stages of this tool was repeated for each stage, yet it should have the same value for both. This submission addresses this issue.
> merged redundant parameters

- tools/eggnog_mapper/eggnog_macros.xml
- tools/eggnog_mapper/eggnog_mapper/README
- tools/eggnog_mapper/eggnog_mapper/eggnog_mapper.xml
- tools/eggnog_mapper/eggnog_mapper/eggnog_mapper_annotate.xml
- tools/eggnog_mapper/eggnog_mapper/eggnog_mapper_search.xml
for rationale see README
TODO:
> eggnog mapper: implement search and annotation phase as additional separate tools

- tools/pepquery2/macros.xml
- tools/pepquery2/pepquery2.xml
- tools/pepquery2/pepquery2_index.xml
The "non enzyme" digestion option results in a much larger search space and deeper recursion within PepQuery2, which can result in a stack overflow. This PR sets the JVM per-thread stack size to 2048KB. The default on Linux x86_64 is 1024KB.
A small typo in the format attribute for input files is corrected as well.
> Increase default JVM stack size for PepQuery2

- tools/eggnog_mapper/eggnog_macros.xml
- tools/eggnog_mapper/eggnog_mapper/eggnog_mapper.xml
- tools/eggnog_mapper/eggnog_mapper/eggnog_mapper_annotate.xml
- tools/eggnog_mapper/eggnog_mapper/eggnog_mapper_search.xml
- tools/metagene_annotator/metagene_annotator.xml
updating the wrapper with Biotools id for BioHackaton project
> add biotools id to eggnog mapper and metaGeneAnnotator

- tools/diann/diann.xml
There is a problem when the user wants to use a custom library. DIA-NN does not ~~find~~recognize the speclib file if it is in the temp folder (with a .dat extension). Added a test to cover this issue.
> Fix DIA-NN

- tools/msconvert/.shed.yml
- tools/msconvert/msconvert.xml
- tools/msconvert/msconvert_macros.xml
Hi all,
This PR links the tools to its bio.tools entry: https://bio.tools/msconvert
Bérénice
> Add bio.tools for msconvert

- tools/pepquery2/macros.xml
- tools/pepquery2/pepquery2.xml
- tools/pepquery2/pepquery2_show_sets.xml
Raw input files do not work with the current PepQuery galaxy implementation. The `-dc` flag must be used to pass a ThermoRawFileParser executable to pepquery, which will require further modifications to the pepquery recipe.
For the time being, remove this option.
> Remove raw file option from PepQuery2

- tools/fragpipe/macros.xml
In recent changes I made these became partially uppercase.
The input datatype seems to be case-insensitive in the history / tests context, but we just caught this when building a workflow. The FragPipe step won't accept mzml inputs because these strings are not fully lowercase.
> Lower-case mzml and mzxml input datatypes

- tools/morpheus/.shed.yml
- tools/morpheus/macros.xml
- tools/morpheus/morpheus.xml
FOR CONTRIBUTOR:
[x]I have read the [CONTRIBUTING.md](https://github.com/galaxyproject/tools-iuc/blob/master/CONTRIBUTING.md) document and this tool is appropriate for the tools-iuc repo.
[x]License permits unrestricted use (educational + commercial)
[x]This PR adds a new tool or tool collection
[x]This PR updates an existing tool or tool collection
[]This PR does something else (explain below)
Background:
The morpheus wrapper does not have the parameter (p) which allows user to select enzyme to be used in the morpheus search process. The option p is listed in https://cwenger.github.io/Morpheus/args.html . 
In addition to include the p option in the wrapper. I have tidied up the morpheus wrapper by creating a macro file for tool version , tokens, values and enzyme list for the paramters …
> add enzyme list to morpheus tool

- tools/fragpipe/macros.xml
I removed this option when I overlooked that mono is already a dependency of the MSFragger recipe. The Galaxy tool can in-fact take `thermo.raw` files directly - we have run local jobs with this option already.
> Add thermo.raw as an Accepted Datatype for Scan File.

- tools/msconvert/msconvert.xml
- tools/msconvert/msconvert_macros.xml
Fixes
```
NotFound: cannot find 'input_ident' while searching for 'data_processing.precursor_refinement.input_ident.ext'
File "galaxy/jobs/runners/__init__.py", line 297, in prepare_job
job_wrapper.prepare()
File "galaxy/jobs/__init__.py", line 1256, in prepare
) = tool_evaluator.build()
File "galaxy/tools/evaluation.py", line 588, in build
global_tool_logs(self._build_command_line, config_file, "Building Command Line")
File "galaxy/tools/evaluation.py", line 98, in global_tool_logs
raise e
File "galaxy/tools/evaluation.py", line 94, in global_tool_logs
return func()
File "galaxy/tools/evaluation.py", line 611, in _build_command_line
command_line = fill_template(
File "galaxy/util/template.py", line 115, in fill_template
return fill_template(
File "galaxy/util/template.py", line 115, in …
```
> Fix boolean to select bugs in msconvert

- tools/qupath_roi_splitter/qupath_roi_splitter.py
- tools/qupath_roi_splitter/qupath_roi_splitter.xml
This version fixes the PNG output, changed the datatype of the coordinates to tabular and added a fix for a special case (LMD data).
> Fix for QuPath ROI Splitter (v0.3.1)

- tools/qupath_roi_splitter/qupath_roi_splitter.py
- tools/qupath_roi_splitter/qupath_roi_splitter.xml
The update fixes a problem with the filling of ROIs.
> Update QuPath ROIsplitter to v0.3.2

- tools/fragpipe/fragpipe.xml
- tools/fragpipe/macros.xml
Two options in IonQuant were incorrectly defined, causing the tool to fail immediately. I've fixed the automated test as well to cover this section.
> Fix IonQuant Options in FragPipe

- tools/uniprotxml_downloader/.lint_skip
- tools/uniprotxml_downloader/.shed.yml
- tools/uniprotxml_downloader/macros.xml
- tools/uniprotxml_downloader/uniprotxml_downloader.py
- tools/uniprotxml_downloader/uniprotxml_downloader.xml
- switch from `stream` to `search` API (`stream` only supports small datasets https://www.uniprot.org/help/api_queries)
- add TSV output (possible columns are derived via a call to the uniprot API :))
- small wording changes
> Uniprot improvements
